### ISSUE TITLE
Package error while importing the project in TIBCO BE studio 5.2

### ISSUE THREAD

**Issue by DeepikaKhetan** [AntAreS24/iProcessDecisionsBEPlugin#1]
Hi, I am facing issue while building the project in Manifest.mf/Dependencies there are few packages missing. Like mentioned below. Could you please let me know if we can import this code in 5.2 studio and it will work fine. if not, could you let me know the JARs that we need to include in our classpath and where to find the JARs.
com.tibco.cep.datamodeling;bundle-version="5.4.0",
 com.tibco.cep.datamodeling.common;bundle-version="5.4.0",
 com.tibco.cep.decision.table.capabilities;bundle-version="5.4.0",
 com.tibco.cep.decision.table.common;bundle-version="5.4.0",
 com.tibco.cep.decision.table.core;bundle-version="5.4.0",
 com.tibco.cep.decision.table.ui;bundle-version="5.4.0",
 com.tibco.cep.decision.tree.common;bundle-version="5.4.0",
 com.tibco.cep.decision.tree.core;bundle-version="5.4.0",
 com.tibco.cep.decision.tree.ui;bundle-version="5.4.0",
 com.tibco.cep.diagramming;bundle-version="5.4.0",
 com.tibco.cep.eventstreamprocessing;bundle-version="5.4.0",
 com.tibco.cep.eventstreamprocessing.common;bundle-version="5.4.0",
 com.tibco.cep.liveview;bundle-version="5.4.0",
 com.tibco.cep.rt;bundle-version="5.4.0",
 com.tibco.cep.security;bundle-version="5.4.0",
 com.tibco.cep.sharedresource;bundle-version="5.4.0",
 com.tibco.cep.sharedresource.ascon;bundle-version="5.4.0",
 com.tibco.cep.sharedresource.hawk;bundle-version="5.4.0",
 com.tibco.cep.studio.application;bundle-version="5.4.0",
 com.tibco.cep.studio.cli;bundle-version="5.4.0",
 com.tibco.cep.studio.cluster.topology;bundle-version="5.4.0",
 com.tibco.cep.studio.common;bundle-version="5.4.0",
 com.tibco.cep.studio.core;bundle-version="5.4.0",
 com.tibco.cep.studio.dbconcept;bundle-version="5.4.0",
 com.tibco.cep.studio.debug.core;bundle-version="5.4.0",
 com.tibco.cep.studio.debug.ui;bundle-version="5.4.0",
 com.tibco.cep.studio.decision.table.ui;bundle-version="5.4.0",
 com.tibco.cep.studio.mapper;bundle-version="5.4.0",
 com.tibco.cep.studio.mapper.ui;bundle-version="5.4.0",
 com.tibco.cep.studio.rms.core;bundle-version="5.4.0",
 com.tibco.cep.studio.rms.ui;bundle-version="5.4.0",
 com.tibco.cep.studio.streambase;bundle-version="5.4.0",
 com.tibco.cep.studio.tester.core;bundle-version="5.4.0",
 com.tibco.cep.studio.tester.ui;bundle-version="5.4.0",
 com.tibco.cep.studio.ui;bundle-version="5.4.0",
 com.tibco.cep.studio.ui.editors;bundle-version="5.4.0",
 com.tibco.cep.studio.ui.navigator;bundle-version="5.4.0",
 com.tibco.cep.studio.ui.statemachine;bundle-version="5.4.0",
 com.tibco.cep.studio.util;bundle-version="5.4.0",
 com.tibco.cep.studio.wizard.as;bundle-version="5.4.0",
 com.tibco.cep.studio.wizard.hawk;bundle-version="5.4.0",
 com.tibco.cep.studio.ws;bundle-version="5.4.0",
 com.tibco.cep.thirdparty;bundle-version="5.4.0",
 com.tibco.cep.tpcl;bundle-version="5.4.0",
 com.tibco.genxdm.extras;bundle-version="1.3.0",
 com.tibco.genxdm.processor.xslt.functions;bundle-version="1.2.100",
 com.tibco.genxdm.processor.xslt.processor;bundle-version="1.2.100",
 com.tibco.tibcoxml.lex.yap.eclipse;bundle-version="5.60.100",
 com.tibco.tibcoxml.net.eclipse;bundle-version="5.60.100",
 com.tibco.tibcoxml.util.eclipse;bundle-version="5.60.100",
 com.tibco.xml.cxf.common;bundle-version="1.3.200",
 com.tibco.xml.cxf.ootb;bundle-version="1.3.200",
 com.tibco.xml.cxf.ootb.runtime;bundle-version="1.3.200",
 com.tibco.xml.cxf.runtime;bundle-version="1.3.200",
 com.tibco.xml.cxf.wizard;bundle-version="1.2.100",
 com.tibco.xml.dictionaryapi;bundle-version="1.0.0",
 com.tibco.xml.mappermodel;bundle-version="1.0.700",
 com.tibco.xml.mappermodel.emfapi;bundle-version="1.0.700",
 com.tibco.xml.mapperui;bundle-version="1.0.700",
 com.tibco.xml.mapperui.emfapi;bundle-version="1.0.700",
 com.tibco.xml.xmodel;bundle-version="1.0.900",

**Comment by AntAreS24** [comment]
Hi Deepak,

No, you MUST have version 5.4.0 of TIBCO BusinessEvents for this to work since I'm using specific libraries from that version.

**Comment by DeepikaKhetan** [comment]
Hi Amiot,

I have changed those versioning to 5.2.0, and I am able to resolve many of them. but below are still pending. Do you happen to know where will I find the rest of the JARs?
 com.tibco.cep.eventstreamprocessing;bundle-version="5.2.0",
 com.tibco.cep.eventstreamprocessing.common;bundle-version="5.2.0",
 com.tibco.cep.liveview;bundle-version="5.2.0",
 com.tibco.cep.datamodeling;bundle-version="5.2.0",
 com.tibco.cep.datamodeling.common;bundle-version="5.2.0",
 com.tibco.cep.studio.dbconcept;bundle-version="5.2.0",
 com.tibco.cep.studio.decision.table.ui;bundle-version="5.2.0",
 com.tibco.cep.studio.ui.statemachine;bundle-version="5.2.0",
 com.tibco.genxdm.extras;bundle-version="1.3.0",
 com.tibco.genxdm.processor.xslt.functions;bundle-version="1.2.100",
 com.tibco.genxdm.processor.xslt.processor;bundle-version="1.2.100",
 com.tibco.tibcoxml.lex.yap.eclipse;bundle-version="5.60.100",
 com.tibco.tibcoxml.net.eclipse;bundle-version="5.60.100",
 com.tibco.tibcoxml.util.eclipse;bundle-version="5.60.100",
 com.tibco.xml.cxf.common;bundle-version="1.3.200",
 com.tibco.xml.cxf.ootb;bundle-version="1.3.200",
 com.tibco.xml.cxf.ootb.runtime;bundle-version="1.3.200",
 com.tibco.xml.cxf.runtime;bundle-version="1.3.200",
 com.tibco.xml.cxf.wizard;bundle-version="1.2.100",
 com.tibco.xml.dictionaryapi;bundle-version="1.0.0",
 com.tibco.xml.mappermodel;bundle-version="1.0.700",
 com.tibco.xml.mappermodel.emfapi;bundle-version="1.0.700",
 com.tibco.xml.mapperui;bundle-version="1.0.700",
 com.tibco.xml.mapperui.emfapi;bundle-version="1.0.700",
 com.tibco.xml.xmodel;bundle-version="1.0.900",

**Comment by AntAreS24** [comment]
Eventstream Processing, LiveLiew and Data Modeling are extensions that are usually installed with TIBCO Enterprise Edition or downloaded and installed separately.

Version 5.4.0 packages those automatically for you now, but 5.2.0 didn't. Most likely, you only have BE Standard edition installed, or you have it with some (but not all) the modules.

**Comment by DeepikaKhetan** [comment]
Yeah, I understand that. But do you happen to know where will I find the rest of the JARs? or Could you please zip all the JARs and attach it if possible for you?

**Comment by AntAreS24** [comment]
:-) Sorry, I'm currently not working with TIBCO, so I don't have access to the software. If you have access to BE 5.2, you should ask the person responsible for the TIBCO download to give you access to those extensions. If you (or your customer) have the right license, you can easily download and install them.

I don't believe I rely on EventStream Processing or LiveView for this plugin. Not sure about Data Modeling. So you could try to remove those dependencies and see if it works?
