### ISSUE TITLE
Hi Amiot, Process to launch

### ISSUE THREAD

**Issue by DeepikaKhetan** [AntAreS24/iProcessDecisionsBEPlugin#2]
I have installed BE 5.4, and imported the code. There is no error in the code.

But while running launch file as BE plugin Eclipse , it is throwing multiple error. Do we need to configure anything before launching the file? Could you please help here ? 

Thanks,
Deepika

**Comment by AntAreS24** [comment]
You fixed it?

**Comment by DeepikaKhetan** [comment]
Yes, it is working now :)
